// <auto-generated />
using System;
using BadgeCatalog.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadgeCatalog.Adapters.Migrations
{
    [DbContext(typeof(BadgeCatalogDbContext))]
    partial class BadgeCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BadgeCatalog.Domain.Aggregates.BadgeClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BadgeClasses", (string)null);
                });

            modelBuilder.Entity("BadgeCatalog.Domain.Aggregates.BadgeClass", b =>
                {
                    b.OwnsOne("BadgeCatalog.Domain.ValueObjects.BadgeCriteria", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("BadgeClassId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Narrative")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CriteriaNarrative");

                            b1.HasKey("BadgeClassId");

                            b1.ToTable("BadgeClasses");

                            b1.WithOwner()
                                .HasForeignKey("BadgeClassId");
                        });

                    b.OwnsOne("BadgeCatalog.Domain.ValueObjects.BadgeImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("BadgeClassId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ImageUrl");

                            b1.HasKey("BadgeClassId");

                            b1.ToTable("BadgeClasses");

                            b1.WithOwner()
                                .HasForeignKey("BadgeClassId");
                        });

                    b.Navigation("Criteria")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
