// <auto-generated />
using System;
using Issuance.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Issuance.Adapters.Migrations
{
    [DbContext(typeof(IssuanceDbContext))]
    [Migration("20260401215616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Issuance.Domain.Aggregates.Assertion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BadgeClassId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assertions", (string)null);
                });

            modelBuilder.Entity("Issuance.Domain.Aggregates.Assertion", b =>
                {
                    b.OwnsOne("Issuance.Domain.ValueObjects.RecipientIdentity", "Recipient", b1 =>
                        {
                            b1.Property<Guid>("AssertionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("HashedEmail")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RecipientHashedEmail");

                            b1.HasKey("AssertionId");

                            b1.ToTable("Assertions");

                            b1.WithOwner()
                                .HasForeignKey("AssertionId");
                        });

                    b.Navigation("Recipient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
